keycloak:
  image: jboss/keycloak:3.4.3.Final
  links:
    - mysql:mysql
  ports:
    - "8080:8080"
  env_file: keycloak/keycloak.env

mysql:
  image: mysql
  env_file: mysql/mysql.env

openldap:
  image: dinkel/openldap
  ports:
    - "389:389"
  env_file: openldap/openldap.env
  volumes:
    - ./openldap:/etc/ldap.dist/prepopulate

